---
roles:

  base_1536mb_ram:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1536]

  base_1024mb_ram:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]

  master_base:
    synced_folders:
      - host_path:  'puppet'
        guest_path: '/tmp/puppet'
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: shell
        inline: "/opt/puppet/bin/puppet config set modulepath /etc/puppetlabs/puppet/modules:/tmp/puppet/modules:/opt/puppet/share/puppet/modules/"
      - type: shell
        inline: '/opt/puppet/bin/puppet module install puppetlabs/pe_gem --version 0.0.1'
      - type: shell
        inline: '/bin/cp /tmp/puppet/manifests/site.pp /etc/puppetlabs/puppet/manifests/site.pp'

  master:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
#        version: '3.2.0'

  windows_agent:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - type: pe_bootstrap
        version: '3.2.0'
        master: 'puppet-master'

  agent:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_bootstrap
#        version: '3.2.0'
        master: 'puppet-master' 

  centos: 
    provisioners:
      - type: shell
        inline: 'service iptables stop; chkconfig iptables off;'

  dhcp_nat:
    provisioners:
      - type: shell
        inline: 'iptables -F'
      - type: shell
        inline: 'iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE'
      - type: shell 
        inline: 'service iptables save'
      - type: shell
        inline: 'service iptables restart'
