---
roles:

  base:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1536]

  master:
    synced_folders:
      - host_path:  'puppet'
        guest_path: '/tmp/puppet'
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: shell
        inline: "/opt/puppet/bin/puppet config set modulepath /etc/puppetlabs/puppet/modules:/tmp/puppet/modules:/opt/puppet/share/puppet/modules/"
      - type: shell
        inline: '/opt/puppet/bin/puppet module install puppetlabs/pe_gem --version 0.0.1'
      - type: shell
        inline: '/bin/cp /tmp/puppet/modules/razor_node_classification/files/site.pp /etc/puppetlabs/puppet/puppet.conf'

  master320:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: :master
        version: '3.2.0'

  windows_agent:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - type: pe_bootstrap
        version: '3.2.0'
        master: 'puppet-master'

  agent_320:
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: pe_bootstrap
        version: '3.2.0'
        master: 'puppet-master' 

  centos: 
    provisioners:
      - type: shell
        inline: 'service iptables stop; chkconfig iptables off;'

